---
name: Linting and Formatting

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  shell:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-shell-code-quality.yaml@dp/add-code-quality-workflows

  python:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-python-code-quality.yaml@dp/add-code-quality-workflows

  yaml:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-yaml-code-quality.yaml@dp/add-code-quality-workflows

  dockerfile:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-dockerfile-code-quality.yaml@dp/add-code-quality-workflows
